
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DevOps.DataEntities.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Branch
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Branch()
    {

        this.BuildProjects = new HashSet<BuildProject>();

        this.ReleaseProjects = new HashSet<ReleaseProject>();

    }


    public int BranchId { get; set; }

    public string BranchName { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public Nullable<byte> Mejor_Version { get; set; }

    public Nullable<byte> Minor_Version { get; set; }

    public Nullable<int> Build_Version { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BuildProject> BuildProjects { get; set; }

    public virtual Project Project { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReleaseProject> ReleaseProjects { get; set; }

}

}
