//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOps.DataEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionId { get; set; }
        public Nullable<byte> RoleId { get; set; }
        public Nullable<int> SubMenuId { get; set; }
        public byte[] Read { get; set; }
        public byte[] Write { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual SubMenu SubMenu { get; set; }
    }
}
