
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DevOps.DataEntities.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Project()
    {

        this.BuildProjects = new HashSet<BuildProject>();

        this.Branches = new HashSet<Branch>();

    }


    public int ProjectId { get; set; }

    public string ProjectName { get; set; }

    public string SolutionName { get; set; }

    public Nullable<int> OrganisationId { get; set; }

    public string SourceURL { get; set; }

    public string FileFormat { get; set; }

    public string Status { get; set; }

    public string Type { get; set; }

    public string Plateform { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> LastModifiedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public System.DateTime LastModifiedDate { get; set; }



    public virtual Organisation Organisation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BuildProject> BuildProjects { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Branch> Branches { get; set; }

}

}
