//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOps.DataEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseProject
    {
        public int ReleaseProjectId { get; set; }
        public Nullable<int> ServerBuildId { get; set; }
        public Nullable<int> ReleaseBy { get; set; }
        public Nullable<byte> Mejor_Version { get; set; }
        public Nullable<byte> Minor_Version { get; set; }
        public Nullable<int> Build_Version { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        public virtual ServerBuild ServerBuild { get; set; }
        public virtual User User { get; set; }
    }
}
