
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DevOps.DataEntities.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ReleaseProject
{

    public int ReleaseProjectId { get; set; }

    public Nullable<int> BuildId { get; set; }

    public Nullable<int> ReleaseBy { get; set; }

    public Nullable<int> ServerId { get; set; }

    public Nullable<System.DateTime> ReleaseDate { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string Status { get; set; }



    public virtual BuildProject BuildProject { get; set; }

    public virtual PackageRelease PackageRelease { get; set; }

    public virtual ServerConfig ServerConfig { get; set; }

    public virtual User User { get; set; }

}

}
