
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DevOps.DataEntities.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ReleaseProject
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ReleaseProject()
    {

        this.ReleaseProjectPackages = new HashSet<ReleaseProjectPackage>();

    }


    public int ReleaseProjectId { get; set; }

    public string ReleaseName { get; set; }

    public int ServerBuildId { get; set; }

    public int BranchId { get; set; }

    public int ReleaseBy { get; set; }

    public System.DateTime ReleaseDate { get; set; }

    public string Status { get; set; }

    public string DownloadURL { get; set; }

    public string ReleaseNotes { get; set; }



    public virtual Branch Branch { get; set; }

    public virtual ServerBuild ServerBuild { get; set; }

    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReleaseProjectPackage> ReleaseProjectPackages { get; set; }

}

}
