//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOps.DataEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerBuild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerBuild()
        {
            this.ReleaseProjects = new HashSet<ReleaseProject>();
        }
    
        public int ServerBuildId { get; set; }
        public Nullable<int> BuildId { get; set; }
        public Nullable<int> ServerId { get; set; }
        public Nullable<int> PublishedBy { get; set; }
        public Nullable<byte> Mejor_Version { get; set; }
        public Nullable<byte> Minor_Version { get; set; }
        public Nullable<int> Build_Version { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
    
        public virtual BuildProject BuildProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseProject> ReleaseProjects { get; set; }
        public virtual ServerConfig ServerConfig { get; set; }
        public virtual User User { get; set; }
    }
}
