//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOps.DataEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServerConfig()
        {
            this.ServerBuilds = new HashSet<ServerBuild>();
            this.ServerCredentials = new HashSet<ServerCredential>();
        }
    
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public string IPAddress { get; set; }
        public string RAM { get; set; }
        public string Processer { get; set; }
        public string OS { get; set; }
        public string Version { get; set; }
        public Nullable<int> OrganisationId { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerBuild> ServerBuilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerCredential> ServerCredentials { get; set; }
    }
}
