
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DevOps.DataEntities.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SubMenu
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SubMenu()
    {

        this.Permissions = new HashSet<Permission>();

    }


    public int SubMenuId { get; set; }

    public Nullable<int> MainMenuId { get; set; }

    public string SubMenuName { get; set; }



    public virtual MainMenu MainMenu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Permission> Permissions { get; set; }

}

}
